version: '3'
services:
  app:
    image: node:11
    container_name: "id-card-detection-api"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    command: npm start
    ports:
      - 0.0.0.0:4000:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: "admin"
      DB_PASSWORD: "adminpw"
      DB_DATABASE: "idcarddetection"
    links:
      - db
  db:
    image: "mysql:5.7.24"
    container_name: "id-card-detection-db"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "adminpw"
      MYSQL_DATABASE: "idcarddetection"